#!/usr/bin/env sh

DIR=$1
OUTFILE="$DIR/`basename $2`"

. $2

empty() {
	test -z "$(echo $1 | tr -d '[:space:]')"
}

update() {
	BUF="$(action)"
	if empty "$BUF"; then
		rm -f $OUTFILE
	else
		echo "$BUF" > $OUTFILE
		xsetroot -name "`sed "1n;s/^/ ╲ /g" $DIR/* | tr -d '\n'`"
	fi
}

update
while condition; do
	update
done

