#!/usr/bin/env sh

cd `dirname $0`

DIR="/run/user/`id -u`/status"
rm -rf "$DIR"
mkdir -p "$DIR"

update() {
	xsetroot -name "$(paste  $DIR/* | sed -E 's/\t+/ ╲ /g')"
}

runmodule() {
	cmd="$1"
	modulename="$(basename "$cmd")"
	modulepath="$(which "$cmd")"
	statefile="$DIR/$modulename"
	while test -x "$modulepath" && IFS= read -r line; do
		echo $line > "$statefile"
		update
	done < <(stdbuf -oL $cmd) # stdbuf prevents buffering so output is always read line-by-line
	# using the < <() trick to make exiting easier.

	rm "$statefile"

}

cleanup() {
	rm -r "$DIR"
	xsetroot -name "statusbar stopped"
	trap - SIGTERM && kill -- -$$
}
trap "cleanup" SIGINT SIGTERM EXIT

for MODULE in `find modules.d/ -executable -type f`; do
	runmodule $MODULE &
done

wait
