#!/usr/bin/env bash

cd `dirname $0`

# this directory is used by systemd for user specific memory
# any tmpfs or ramfs would work just as well, though any filesystem can be used
DIR="/run/user/`id -u`/status"
rm -rf "$DIR"

mkdir -p "$DIR"

trap 'jobs -p | xargs -r kill' EXIT #clean up children

for MODULE in `find modules.d/*`; do
	echo $MODULE
	./common $DIR $MODULE &
done

wait
