#!/usr/bin/env sh

mpstat -P ALL -o JSON 1 |
jq --stream --raw-output --unbuffered '
	fromstream(6|truncate_stream(inputs)) |
	reduce .[] as $item (
		"";
		.  + " " + ($item.idle | tostring)
	)
' | awk '
	function numtobar (f) {
		if ( f < 2 )
			return "▓";
		if ( f < 10 )
			return "█";
		if ( f < 20 )
			return "▇";
		if ( f < 30 )
			return "▆";
		if ( f < 40 )
			return "▅";
		if ( f < 50 )
			return "▄";
		if ( f < 60 )
			return "▃";
		if ( f < 70 )
			return "▂";
		if ( f < 80 )
			return "▁";
		if ( f < 90 )
			return "_";
		return "";
	}
	{
		for(i=1;i<NF;i++)
			printf numtobar($i) ;
		printf "\n"
	}
'

